server:
  port: 8000

spring:
  application:
    name: gateway
  config:
    import: "optional:consul:"
  cloud:
    gateway:
      routes:
        - id: DatabaseService
          uri: "http://localhost:8081/"
          predicates:
            - Path=/ #path here
      globalcors:
        cors-configurations:
          '[/**]':
            allowed-origins:
              - "http://localhost:3000"
            allowed-headers:
              - "*"
            allowed-methods:
              - "GET"
              - "POST"
              - "OPTIONS"
      default-filters:
        - name: Retry
          args:
            retries: 3
            methods: GET, POST